### ISSUE TITLE
Make ontoGrapher project oriented

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#7] opened 2019-11-01 04:47 UTC
Currently, ontoGrapher is diagram oriented - in the main menu, a user is able to create a new diagram, save it and load it. However, ontoGrapher must be project oriented. The user shall be able to create a new project, save it and load it. 

A project has three parts:
- the set of stereotypes for classes and associations
- ontology models
- one or more diagrams

The core of the project are the ontology models. There are one or more imported models which are read only. And there are one or more models which are defined in the project by the user. Defining model means specification of its metadata and definition of its elements - classes and associations with stereotypes from the set of stereotypes.

The diagrams are views on the model. The user shall be able to create many diagrams. In each diagram, the user may visualize selected parts of the models drag&drop-ing classes and defining their visual layout.

The UI shall enable the user to open and close the diagrams. Not all diagrams need to be open. The user shall be able to see somewhere the list of diagrams and open a selected diagram. This also means that diagrams should have titles.

**Comment by bindetad** [comment] 2019-11-19 10:30
Status as of b693b610b8797c4d349f5b25b63a3a8d040eb8b8:
The component's element panel has been extended by two tabs: 
![image](https://user-images.githubusercontent.com/56399637/69138315-b8e06880-0abe-11ea-91fa-7d3369e81df2.png)
The first two are imports of stereotypes as described in #1, whereas the "P&M" tab represents packages with models and the "D" tab represents diagrams.

Whenever the user drags stereotypes onto the canvas, a new class is created in the root package. This is reflected in the P&M tab: 
![image](https://user-images.githubusercontent.com/56399637/69138464-078e0280-0abf-11ea-9b10-7e1c37ce7404.png)

From here, the user can either
* Delete packages
* Add new empty packages
* Switch to packages or models
* Manage packages or models

Any elements shown here can be dragged onto the canvas. The user can also see imported models as defined in #1. Models are designated with the 📄 icon and packages are designated with the ✏ icon. Models cannot be modified.

Clicking on the "Manage" button opens a modal dialogue: 
![image](https://user-images.githubusercontent.com/56399637/69138767-8c791c00-0abf-11ea-8f5f-d6a4c2a296e1.png)

The user can use this modal to 
* Delete or move classes (if in package),
* See connections to other classes (if applicable).

The final tab, "D", describes diagrams. Here, the user can switch between diagrams or manage them within a modal dialogue in the project. The diagrams are saved in memory and are loaded at the user's request.

**Comment by martinnec** [comment] 2019-12-04 11:00
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontroGrapher #2](https://trello.com/c/jjYcBXyE/65-pr%C3%A1ce-na-issues-v-ontrographer-2)

**Comment by blcham** [comment] 2019-12-10 12:51
- adding/removing/switching packages works
- I was not able to test "Manage packages or models". When I click to "Manage" within M&D i see always empty window:
![Selection_001](https://user-images.githubusercontent.com/3962237/70530862-13b42f80-1b54-11ea-8105-7516944ddf70.jpg)

- Clicking on VS-GOV node within "P&M" gives me error:
```
TypeError: Cannot read property 'cs' of undefined
    at bundle.js:74
    at Array.map (<anonymous>)
    at t.value (bundle.js:74)
    at Ba (bundle.js:50)
    at Da (bundle.js:50)
    at eu (bundle.js:50)
    at _u (bundle.js:50)
    at mu (bundle.js:50)
    at su (bundle.js:50)
    at bundle.js:50
```

**Comment by bindetad** [comment] 2019-12-17 00:49
VS-GOV error should be fixed as of 5343096fdbafaeebbeb9a4e34a3e6bde80ee1626, please check.

Package management shows an empty dialogue if there are no instances in the given package. To add instances, [drag them from the first tab onto the canvas](https://github.com/opendata-mvcr/ontoGrapher/wiki/Basic-modeling#creating-instances). Perhaps I should make it so that you can't access the dialogue unless there is at least one instance present.

**Comment by blcham** [comment] 2020-01-04 19:09
Errors from the above were fixed. 

Last issue to fixed:
There is an issue when I add class to a diagram and change its name. New name is not reflected in list of classes as can be seen here :
![Selection_003](https://user-images.githubusercontent.com/3962237/71770507-7f0fd800-2f2d-11ea-9c0c-d10b3de81fb5.jpg)

**Comment by bindetad** [comment] 2020-01-05 12:53
I can't seem to reproduce the issue. Here's what I tried:
![example](https://user-images.githubusercontent.com/56399637/71780446-ae245900-2fc2-11ea-8b0f-079d95fcbd4e.gif)

**Comment by blcham** [comment] 2020-01-05 20:09
This is because I did not use save button, see #15.

Closing the issue.

**Closed by blcham** 2020-01-05 20:09 UTC
Labels: enhancement
