### ISSUE TITLE
Adding individual items from the list of connections to the diagram

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#236] opened 2021-02-17 08:50 UTC
Add a possibility to add an individual item from the list of connections of an item chosen in a diagram:

![image](https://user-images.githubusercontent.com/4235208/108179008-63ea3280-7105-11eb-8380-f3c46cc31d4d.png)

So for example, for "Řidič", I would like to be able to say that I want to add "má vztažený prvek 1" "řídí vozidlo". Currently, I can only say to add all which often means that I have to remove a lot of items from the diagram when I want to see only few items.

**Comment by psiotwo** [comment] 2021-02-17 08:59
duplicate of https://github.com/opendata-mvcr/ontoGrapher/issues/207

**Closed by psiotwo** 2021-02-17 08:59 UTC
Labels: enhancement
