### ISSUE TITLE
Diagram layout not preserved

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#87] opened 2020-08-14 14:36 UTC
I had this

![image](https://user-images.githubusercontent.com/4235208/90260703-2a7df500-de4c-11ea-9c1b-b0ff683408fe.png)

When I reopened the workspace I got this

![image](https://user-images.githubusercontent.com/4235208/90260802-55684900-de4c-11ea-9bbc-54fc697d9abb.png)

**Comment by martinnec** [comment] 2020-08-15 13:53
It seems that this problem also happens when I switch between diagrams in a workspace. I have 4 diagrams. OFN Témata dizertačních prací was nicely layouted. I then switched to another diagram and returned back to OFN Témata dizertačních prací and I got this:

![image](https://user-images.githubusercontent.com/4235208/90313774-72b21b80-df0f-11ea-8cb6-267b32859c0c.png)

**Comment by bindetad** [comment] 2020-08-30 16:56
The c444357 revision saves the diagram layout more often, which in my experience results in predictable diagram layouts.

**Comment by psiotwo** [comment] 2020-09-17 13:24
Cannot reproduce any lost layouts during working with OntoGrapher either, so closing at this point.

**Closed by psiotwo** 2020-09-17 13:24 UTC
Labels: bug
