### ISSUE TITLE
Deleted or hidden elements shown again in a diagram after workspace reopened from the control panel.

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#141] opened 2020-10-29 20:13 UTC
In workspace "GSGoV - témata dizertačních prací" I have the following diagram:

![image](https://user-images.githubusercontent.com/4235208/97626768-a2f75980-1a2a-11eb-8c00-b6b997a75836.png)

Ontographer tells me that it was saved successfully.

However, when I reopen the workspace from the control panel, I can see a different diagram:

![image](https://user-images.githubusercontent.com/4235208/97626958-f2d62080-1a2a-11eb-978d-ca8fe786f77a.png)

- (yellow) There is relation "má vztažený prvek 2" from "má konzultanta" to "Výzkumník". I explicitly deleted this relation from the model by pressing the red cross button at the relation. However, it was not deleted as we can see.
- (blue) I explicitly hid "Věc" but it is visible after reopening the workspace
- (orange) A line which was broken once and narrower later is broken again after the reload.

**Comment by bindetad** [comment] 2020-11-02 00:58
In 28081f3, I have worked on the "yellow" and "blue" issues. Will work on the "orange" issue.

**Comment by bindetad** [comment] 2020-11-02 10:20
In d233aab, I have also fixed the "orange" issue.

**Comment by psiotwo** [comment] 2020-11-02 13:00
I can still reproduce the orange behaviour.

**Comment by bindetad** [comment] 2020-11-02 22:00
In efc85fc, the orange issue seems to no longer be happening.

**Comment by psiotwo** [comment] 2020-11-17 23:35
Tested, cannot reproduce any more, so closing.

**Closed by psiotwo** 2020-11-17 23:35 UTC
Labels: bug
