### ISSUE TITLE
Setting a stereotype of an element leads to a blank page and deleting the element

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#85] opened 2020-08-14 13:53 UTC
Workspace: https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1926685862

I created a new diagram "OFN Práce". I moved on the canvas the following elements: Platové podmínky, Částka, plat, minimální plat, maximální plat.

I connected plat with Platové podmínky (má vztažený prvek 1) and Částka (má vztažený prvek 2).

Then I set stereotypes:

<<typ objektu>> for Platové podmínky
<<typ vztahu>> for maximální plat

Then I wanted to set <<typ vztahu>> for plat.

I got a blank page:

![image](https://user-images.githubusercontent.com/4235208/90256192-a1fc5600-de45-11ea-903e-07a239031c84.png)

Then I refreshed the whole page (F5). The workspace was loaded again and the element plat was deleted from the workspace (it is confirmed by the fact that I cannot see it even in Termit).

![image](https://user-images.githubusercontent.com/4235208/90256622-454d6b00-de46-11ea-9166-917475933b19.png)

**Comment by bindetad** [comment] 2020-08-30 16:55
This seems very similar to #76. Revision c444357 is more crash-proof.

**Comment by psiotwo** [comment] 2020-09-17 13:48
I tested it and was not able to reproduce the problem, so closing.

**Closed by psiotwo** 2020-09-17 13:48 UTC
Labels: bug
