### ISSUE TITLE
Term from Termit not fully represented in Ontographer

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#81] opened 2020-08-14 08:54 UTC
I created a new term in Termit:

![image](https://user-images.githubusercontent.com/4235208/90231797-f7bc0880-de1b-11ea-9f4a-2934c9d8fa46.png)

I openned the workspace in Ontographer and I cannot see its prototype (shall be object type) and its connection to its broader type (člověk)

On this screenshot, you can see the emty list of stereotypes (I expected the object type here)

![image](https://user-images.githubusercontent.com/4235208/90232033-571a1880-de1c-11ea-97f5-2c41d269b186.png)

And here the empty list of connections (I would expect specialization of člověk here)

![image](https://user-images.githubusercontent.com/4235208/90232162-8466c680-de1c-11ea-87b5-fe8e52938543.png)

**Comment by bindetad** [comment] 2020-09-15 05:01
This issue is related to #86, so I will proceed the same way (ask about Termit behaviour, then report back).

**Comment by bindetad** [comment] 2020-09-15 08:37
This is because ufo/object-type is not loaded in ontoGrapher's default configuration. We had considered previously that ontoGrapher would show concept IRIs of concepts that it does not recognize, but that would be made as an enhancement and therefore is not a bug.

**Comment by psiotwo** [comment] 2020-09-17 14:20
TermIt is updated to contain correct prototypes, so this is fixed.

As for the subclassing issue: I don't think we should support skos:broader as a rdfs:subClassOf in ontographer:
- skos:broader is a general vague link, one interpretation of which might be rdfs:subClassOf, but also rdf:type or ufo:isPartOf for example. So while I would not be against showing the hierarchy of terms in the left panel of ontographer, I don't think it would be consistent to show the SKOS links in the model. SKOS and UFO are disjoint and we should keep it IMO.

**Comment by martinnec** [comment] 2020-09-18 13:23
I checked the behaviour and its seems fixed.

**Comment by psiotwo** [comment] 2020-09-18 20:12
Closing, fixed.

**Closed** 2020-09-18 20:12 UTC
Labels: bug
