### ISSUE TITLE
I am not able to select one relationship on a diagram

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#41] opened 2020-04-12 17:11 UTC
I have three classes and two associations. I am able to select one of the relationships using the blue i circle:

![image](https://user-images.githubusercontent.com/4235208/79075155-4aac7480-7cf1-11ea-84ab-f7790d0351a9.png)

But I am not able to select the other one using the same command.

**Comment by martinnec** [comment] 2020-04-12 17:13
Maybe the problem is that I have that relationship twice? Then I do not know why I was able to create it.

![image](https://user-images.githubusercontent.com/4235208/79075212-babafa80-7cf1-11ea-8153-6450bcc97aa4.png)

**Comment by bindetad** [comment] 2020-04-13 08:04
I don't understand what the issue is exactly. Am I reproducing it correctly? (the top relationship has a cardinality just so you know that it recognizes it.)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/56399637/79104022-fc898680-7d6d-11ea-99ca-7200c145fe1e.gif)

**Comment by martinnec** [comment] 2020-04-18 08:50
When I clicked the "i" symbol at the associatoin, it was not selected. But as I have wrote, maybe the problem was that I had the association twice in the model.

**Comment by bindetad** [comment] 2020-04-19 09:47
If by 'the same association twice' you mean 'two instances of [je vlastností] in the diagram' (what is depicted in your screenshot) then that should absolutely be allowed. There was an issue a week or two back in which deleted associations didn't delete properly and still showed up in the 'Connections' tab, which is something I see in your screenshot, but should be fixed at the time of writing this comment. So, I apologize, but I don't know how to reproduce the issue. Could you please produce a video of this or steps to reproduce? Did it maybe show something in the console? Does the video I produced show something different from what you did? Is the bug visual-only (the link didn't turn orange) or did the right panel not appear?

I am really sorry, but I am very confused, since if having two associations of the same type would produce issues, then I am quite sure we would have caught them by now. So apologies that I am not getting what you are saying.

Unfortunately, since we are having [issues with the deployed version of ontoGrapher right now](https://github.com/opendata-mvcr/ontoGrapher/issues/42#issuecomment-615424927), you might have to use the local version for a day or two. The details are in the comment linked above.

**Comment by bindetad** [comment] 2020-09-08 11:58
Closing on request from @martinnec as this has been resolved.

**Closed by bindetad** 2020-09-08 11:58 UTC
Labels: bug
